### ISSUE TITLE
Adapter ist nicht mit Milight Hub auf ESP8266 basis kompatibel

### ISSUE THREAD

**Issue by ghost** [Steiger04/ioBroker.milight-smart-light#11]
Hallo. gibt es die Möglichkeit diesen Adapter mit der Milight Hub kompatibel zu machen?
Der normale Milight adapter vom IoBroker funktioniert damit zwar, aber ist vom Funktionsumfang und der zuverlässigkeit mit mit diesem Vergleichbar.
Konkret geht es um dieses Projekt
https://github.com/sidoh/esp8266_milight_hub

Hardware könnte ich bei bedarf gerne zur verfügung stellen wenn gewünscht

EDIT: Mit den Standartports 5987 funktioniert es. Reagiert dieser Adapter nur auf diesen UDP Port?

**Comment by ghost** [comment]
So wie es aussieht wird dieser adapter nicht mehr dahingehend weiterentwickelt. Schade. Über eine Antwort hätte ich mich trotzdem Gefreut

**Comment by Steiger04** [comment]
@Mazdaracer121 Ich dachte nach Deinem EDIT hätte sich das Thema erledigt. Was fehlt Dir denn jetzt noch?
