### ISSUE TITLE
Loading default into states after instance re-start

### ISSUE THREAD

**Issue by DoraDeu** [Steiger04/ioBroker.milight-smart-light#13]
There is currently a problem when the instance of the adapter get re-startet.
All changed values of the states get lost and the initial default values are loaded into the objects.
That means that all lights are going off when the instance is re-startet. 

Milight-smart-light adapter version: 0.1.9
Admin adapter: 3.5.10
node: 6.14.4
npm: 3.10.10
js-controller: 1.4.2
iobroker is not running as root but as user "iobroker" on a Linux PC (no RPi)

**Comment by Steiger04** [comment]
As of version 0.2.0, the values ​​are retained after a restart, unless a zone has been changed via the admin.
