### ISSUE TITLE
Upadte funktioniert nicht auf 0.2.0

### ISSUE THREAD

**Issue by Ridesa** [Steiger04/ioBroker.milight-smart-light#17]
$ ./iobroker url "https://github.com/Steiger04/ioBroker.milight-smart-light"
install https://github.com/Steiger04/ioBroker.milight-smart-light/tarball/master
npm install https://github.com/Steiger04/ioBroker.milight-smart-light/tarball/master --production --save --prefix "/opt/iobroker" (System call)
npm 
ERR! code ENOGIT
npm ERR! Error while executing:npm ERR! undefined ls-remote -h -t https://github.com/mwittig/node-milight-promise.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-02-13T10_53_23_288Z-debug.log

process exited with code 0

**Comment by Steiger04** [comment]
@Ridesa Problem ist behoben. Du musst noch einmal neu installieren (Version 0.2.1).
