### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by Moormerlander** [Steiger04/ioBroker.milight-smart-light#21]
Mit Version 0.1.8 bekomme ich diese Fehler:

`
host.ioBroker | 2019-04-10 11:38:18.781 | info | Restart adapter system.adapter.milight-smart-light.0 because enabled
-- | -- | -- | --
host.ioBroker | 2019-04-10 11:38:18.780 | error | instance system.adapter.milight-smart-light.0 terminated with code 0 (OK)
Caught | 2019-04-10 11:38:18.780 | error | by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
Caught | 2019-04-10 11:38:18.780 | error | by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2019-04-10 11:38:18.779 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
Caught | 2019-04-10 11:38:18.779 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2019-04-10 11:38:18.778 | error | by controller[0]: at Socket.that.getForeignObject (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:25)
Caught | 2019-04-10 11:38:18.778 | error | by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:830:13)
Caught | 2019-04-10 11:38:18.778 | error | by controller[0]: at createInstancesObjects (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:869:54)
Caught | 2019-04-10 11:38:18.778 | error | by controller[0]: at initAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5289:18)
Caught | 2019-04-10 11:38:18.778 | error | by controller[0]: at Adapter.emit (events.js:185:7)
Caught | 2019-04-10 11:38:18.777 | error | by controller[0]: at emitNone (events.js:86:13)
Caught | 2019-04-10 11:38:18.777 | error | by controller[0]: at Adapter.adapter.on (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:190:3)
Caught | 2019-04-10 11:38:18.777 | error | by controller[0]: at main (/opt/iobroker/node_modules/iobroker.milight-smart-light/main.js:197:21)
Caught | 2019-04-10 11:38:18.776 | error | by controller[0]: at Function.Promise.promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:311:12)
Caught | 2019-04-10 11:38:18.776 | error | by controller[0]: at promisifyAll (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:241:9)
Caught | 2019-04-10 11:38:18.776 | error | by controller[0]: at promisifiableMethods (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:77:5)
Caught | 2019-04-10 11:38:18.775 | error | by controller[0]: at checkValid (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/bluebird/js/release/promisify.js:54:27)
Caught | 2019-04-10 11:38:18.774 | error | by controller[0]: See http://goo.gl/MqrFmX
Caught | 2019-04-10 11:38:18.762 | error | by controller[0]: TypeError: Cannot promisify an API that has normal methods with 'Async'-suffix
host.ioBroker | 2019-04-10 11:38:15.818 | info | instance system.adapter.milight-smart-light.0 started with pid 7016
`

**Comment by Steiger04** [comment]
Wenn Du die 0.1.8'ter weiter nutzen möchtest, muss der js-controller <= v. 1.2.5 sein. Das ist aber nicht zu empfehlen. Du solltest den milight-smart-light Adapter in der aktuellen Version 0.2.5 verwenden.
