### ISSUE TITLE
About zone 0 (all groups) #16

### ISSUE THREAD

**Issue by itProfi** [Steiger04/ioBroker.milight-smart-light#23]
May i repeat my old qustion - are you planned control all 4 group (for example rgb+ww) simultaneously?

**Comment by Steiger04** [comment]
@itProfi At the moment this is not planned. In ioBroker you can set arbitrary states with the required values one after the other with a scene in order to implement your requirements, or did I misunderstand you?

**Comment by itProfi** [comment]
Not quite....I mean, that you create wonderful web apps through web browser..!!
![Скриншот 21-06-2019 105025](https://user-images.githubusercontent.com/6728198/59907079-e2fc0480-9412-11e9-8af8-fd130ea1e9a2.jpg)
But in this app there is no possibility for operate all zones (4) for one bridge. In case, where we have 3-4 group in one room, we must open 4 tabs in app for On or Off each group of light..Is it possible integrate it?
![Скриншот 21-06-2019 105749](https://user-images.githubusercontent.com/6728198/59907319-7df4de80-9413-11e9-9576-96ca430b4cbc.jpg)

**Comment by Steiger04** [comment]
I will include this topic in my ToDo list. A new milight-smart-light version will not be available until the end of autumn.

**Comment by itProfi** [comment]
Ok, thanks!

**Comment by toma315** [comment]
Just if someone is interested ... I had the same problem and worked around it by

  - inserting "zone0" in admin/lib/js/msl-vue.js, numberZones (v6: ['select', 'zone0', 'zone1',....)
  - added Texts for "zone0" to admin/words.js

Actually, this seems to do the trick, at least zone0 ("all") is working for me now ...

**Comment by itProfi** [comment]
@toma315 Thanks, i try it!
