### ISSUE TITLE
Keine HUE Farbänderung wenn "whiteMode" aktiv ist

### ISSUE THREAD

**Issue by ihavenonick** [Steiger04/ioBroker.milight-smart-light#24]
Wie in der Überschrift schon steht, bekomme ich über den DP "HUE" keine Farbänderung zu Stande, wenn ich vorher auf weiß geschaltet hatte. Erst eine Farbänderung über "rgb" macht auch "HUE" wieder aktiv.
Das wirkt sich negativ auf den iQonrol Adapter aus, da ich hier die Farbe nur über den HUE DP ändern kann. RGB wäre mir zwar lieber, aber es stehen eben nur diese Datenpunkte im iQontrol Adapter zur Verfügung:
![grafik](https://user-images.githubusercontent.com/36501310/59974332-30ab7500-95ab-11e9-96f9-7df7d9fe0d43.png)

**Comment by Steiger04** [comment]
Das ist auch richtig so, weil #ffff (also weiß) in HSV-Schreibweise bedeutet: H(hue):[0..360], S(saturation): 0, V(value==brightness): 100. Wenn Du nur hue änderst, bleibt der rgb-Wert immer #ffff, da die saturation==0 ist. Änderst Du nur die brightness (also hue beliebig und saturation==0), erhältst Du einen Grauton, was bei LEDs einem nicht so hellem Weiß entspricht. Erst wenn Du hue und saturation änderst, erhälst Du wieder eine Farbe (bei brighness != 0).

**Comment by ihavenonick** [comment]
Ja weiß ich auch, nur bringt mir das nichts, wenn ich über den Slider im Adapter dann keine Farbe ändern kann, wenn die Lampe auf weiß steht.
Sprich ich muss zuerst im RGB DP eine Änderung vornehmen, damit ich mit dem HUE DP die Farben regeln kann, was etwas blöd ist, da der iQontrol Adapter eben keine Möglichkeit hat RGB zu ändern.

Ist aber auch nicht so tragisch, weil der Entwicklee ein RGB Steuerung auf seiner todo Liste hat und ich dann einfach über RGB das erledige.
Hatte nur gedacht, dass das im Deinem Adapter eventuell so nicht beabsichtigt war.

**Comment by ihavenonick** [comment]
Eine letzte Frage noch, Du schreibst, dass man saturation noch ändern müsste, würde über den iQontrol Adapter sogar funktionieren, nur hat Dein Adapter kein saturation DP. Gibts da ein Trick, oder habe ich Dich falsch verstanden?

**Comment by Steiger04** [comment]
Du nutzt ja auch den RGBW-Typ. Der ist für Strips und LEDs, die nur 65536 Farben darstellen können (saturation immer gleich 100). Wenn Du aber eine 16 mio. COLOR-LED, oder einen entsprechenden Strip-Adapter nutzt, dann solltest Du als Typ fullColor nehmen, dann hast Du auch einen saturation-State.

**Comment by ihavenonick** [comment]
Ich habe die Mi-Light 9W RGB WW Bulb und die bekomme ich eben am besten mit Deinem Adapter zum laufen, oder hast Du ne Idee ob die mit nem anderen Adapter außer dem Mi-Light Adapter auch geht? Die ist mit 1,6Mio Farben angegeben.

**Comment by Steiger04** [comment]
Probier es doch mal mit dem fullColor-Typ.

**Comment by ihavenonick** [comment]
Habe ich schon und dann geht die Lampe nicht mehr. Liegt wohl an der Lampe, trotzdem Danke für die Hilfe und wie geschrieben, der Entwickler plant in seinem Adapter eh ne RGB Unterstützung und dann geht's ja wie gewünscht.
