### ISSUE TITLE
No Actions on the iBOX2

### ISSUE THREAD

**Issue by Peter1980FFM** [Steiger04/ioBroker.milight-smart-light#26]
Hallo,
ich haben mir die IBOX2 gekauft 
Wird auch von IO Broker als Discover bridges: [{"ip":"192.168.122.30","mac":"98:D8:63:70:B9:E6","name":"HF-LPB100","type":"v6"}]
Erkannt.
Steuer Damit eine FUT037
Mit der App Mi Light in der Version 4 alles kein Problem...
Der Adapter findet die IP sagt auch er ist Verbunden
![image](https://user-images.githubusercontent.com/45266139/73263873-d07c5180-41d1-11ea-9ef1-7886b63466cd.png)
In den Objekten auch alle Gut
![image](https://user-images.githubusercontent.com/45266139/73263922-e427b800-41d1-11ea-93b0-9c6ba2c8eac3.png)

im Log steht nichts....

Egal was ich bei den Objekte eingebe, es findet keine Steuerung des RGB Adapters statt.
Auch im Gerät selber habe ich alle Probiert
![image](https://user-images.githubusercontent.com/45266139/73264087-3a94f680-41d2-11ea-928e-a11569dca5e1.png)

Keine Einstellungen helfen....

**Comment by DarthBully** [comment]
Hallöchen,

 

warum ich das als PN bekommen habe weiß ich nicht aber ich versuch mal zu helfen.

 

Der Datenpunkt ONOFF schaltet zwischen an aus hin und her dabei wird der letze Zustand verwendet

 

Der Kanal muss erst eingeschaltet sein, bevor man Farbe oder sowas ändern kann.

Sollte das alles nicht helfen, dann starte erstmal alles neu.

 

An der WLAN-Box brauchst Du nix zu ändern, das funktioniert out of the box.

 

Willst Du den per Siri steuern? Ich weiß aus Erfahrung, dass das Milticast nicht unterbunden werden darf.

Wie ist deine Infrastruktur da aufgestellt? Switche, Router, Firewalls usw?

 

beste Grüße und viel Erfolg

 
 

Gesendet: Dienstag, 28. Januar 2020 um 13:29 Uhr
Von: "Peter1980FFM" <notifications@github.com>
An: "Steiger04/ioBroker.milight-smart-light" <ioBroker.milight-smart-light@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [Steiger04/ioBroker.milight-smart-light] No Actions on the iBOX2 (#26)


Hallo,
ich haben mir die IBOX2 gekauft
Wird auch von IO Broker als Discover bridges: [{"ip":"192.168.122.30","mac":"98:D8:63:70:B9:E6","name":"HF-LPB100","type":"v6"}]
Erkannt.
Steuer Damit eine FUT037
Mit der App Mi Light in der Version 4 alles kein Problem...
Der Adapter findet die IP sagt auch er ist Verbunden

In den Objekten auch alle Gut


im Log steht nichts....

Egal was ich bei den Objekte eingebe, es findet keine Steuerung des RGB Adapters statt.
Auch im Gerät selber habe ich alle Probiert


Keine Einstellungen helfen....
