### ISSUE TITLE
Unterstützung WL-Box1

### ISSUE THREAD

**Issue by madison2007** [Steiger04/ioBroker.milight-smart-light#27]
Die Ibox2 von Milight scheint es nicht mehr zu geben.
Ich habe nur noch die WL-Box1 von MiBoxer bekommen, scheint der nachfolger zu sein.
Wird die neue Box unterstützt?

lg Mad

**Comment by Steiger04** [comment]
@madison2007 Leider nein! -> [bcaro / Miboxer](https://github.com/bcaro/Miboxer)
