### ISSUE TITLE
Update / Neu Installationen nicht Möglich

### ISSUE THREAD

**Issue by Peter1980FFM** [Steiger04/ioBroker.milight-smart-light#31]
Hallo beim Aktualisieren und Neu Installieren bekomme ich folgende fehler:
$ ./iobroker url "https://github.com/Steiger04/ioBroker.milight-smart-light.git"
install https://github.com/Steiger04/ioBroker.milight-smart-light/tarball/4425b8971d25e44228c8f6052a9afd02b94f9e55
NPM version: 6.14.4
npm install https://github.com/Steiger04/ioBroker.milight-smart-light/tarball/4425b8971d25e44228c8f6052a9afd02b94f9e55 --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code ENOENTnpm ERR! syscall spawn gitnpm ERR! path gitnpm ERR! errno ENOENT
npm
 ERR! enoent Error while executing:npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Steiger04/node-milight-promise.gitnpm ERR! enoent npm
 ERR! enoent npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent 

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-05-25T10_02_41_229Z-debug.log
ERROR: host.IoBroker-OpenHab Cannot install https://github.com/Steiger04/ioBroker.milight-smart-light/tarball/4425b8971d25e44228c8f6052a9afd02b94f9e55: 1
ERROR: process exited with code 25

**Comment by Peter1980FFM** [comment]
$ ./iobroker url "https://github.com/Steiger04/ioBroker.milight-smart-light.git" --debug
install https://github.com/Steiger04/ioBroker.milight-smart-light/tarball/4425b8971d25e44228c8f6052a9afd02b94f9e55
NPM version: 6.14.5
npm install https://github.com/Steiger04/ioBroker.milight-smart-light/tarball/4425b8971d25e44228c8f6052a9afd02b94f9e55 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! code
 ENOENTnpm ERR! syscall
 spawn gitnpm
 ERR! 
path gitnpm
 ERR! errno ENOENT
npm
 ERR!
 enoent Error while executing:
npm 
ERR! enoent
 undefined ls-remote -h -t ssh://git@github.com/Steiger04/node-milight-promise.gitnpm ERR!
 enoent 
npm ERR!
 enoent
 npm ERR!
 enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.npm ERR! 
enoent 

npm ERR! A complete log of this run can be found in:npm 
ERR!     /home/iobroker/.npm/_logs/2020-05-25T10_12_03_513Z-debug.log
ERROR: host.IoBroker-OpenHab Cannot install https://github.com/Steiger04/ioBroker.milight-smart-light/tarball/4425b8971d25e44228c8f6052a9afd02b94f9e55: 1
ERROR: process exited with code 25

**Comment by Steiger04** [comment]
Empfehlung wäre alle Instanzen noch einmal zu löschen, dann den Adapter löschen und dann neu über ioBroker-Admin installieren. Was genau bei Dir schief gelaufen ist kann ich Dir nicht sagen, Du bist aber bisher der Einzige mit diesem Problem. Ich habe gerade bei mir auch noch einmal getestet und neu installiert. Klappt alles ohne Probleme. Vielleicht ist bei Deiner ioBroker-Installation ja noch irgendetwas nicht in Ordnung.

Bei einem Update auf v0.6.0 immer auch folgendes **[>>beachten<<](https://steiger04.github.io/milight-smart-light-doku/versionen/#v0-6-0)**.

**Comment by Peter1980FFM** [comment]
Genau das ist ja mein Problem, nach dem das Update immer fehl geschlagen ist, habe ich alles rausgenommen und versuche es zu Installieren egal ob über GIT oder die Adapterliste immer das selbe...
$ ./iobroker add milight-smart-light  --host IoBroker-OpenHab
NPM version: 6.14.4
npm install iobroker.milight-smart-light@0.6.0 --loglevel error --prefix "/opt/iobroker" (System call)
npm
 ERR! code ENOENTnpm ERR!
 syscall spawn gitnpm ERR! path gitnpm ERR! errno ENOENT
npm ERR! enoent Error while executing:npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Steiger04/node-milight-promise.gitnpm ERR! enoent npm ERR! enoent npm ERR! enoent spawn git ENOENTnpm ERR! enoent This is related to npm not being able to find a file.npm ERR! enoent 
npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2020-05-25T16_50_37_961Z-debug.log
ERROR: host.IoBroker-OpenHab Cannot install iobroker.milight-smart-light@0.6.0: 1
ERROR: process exited with code 25
andere Apps gehen ganz normal zu Aktualisieren oder zu Installieren

**Comment by Steiger04** [comment]
Probier mal:
`npm install iobroker.milight-smart-light@0.6.0 --force --loglevel error --prefix "/opt/iobroker"`
im Terminal.

Läuft ioBroker unter Linux oder Windows bei Dir?

**Comment by Peter1980FFM** [comment]
[2020-05-25T17_03_03_387Z-debug.log](https://github.com/Steiger04/ioBroker.milight-smart-light/files/4678216/2020-05-25T17_03_03_387Z-debug.log)
leider kein erfolg hier das log
Linux Rasperry 4

**Comment by Steiger04** [comment]
Der erste Fehler lautet:
`fetchPackageMetaData undefined ls-remote`
ls-remote sagt mir gerade gar nichts. Hast Du mal handisch irgendetwas an der ioBroker-Installation gemacht? Das ist jetzt natürlich fischen im trüben.
Du kannst ja mal eine Testinstallation von ioBroker neu aufsetzen und dann den Adpater installieren. Wenn dann der Fehler immer noch auftritt werde ich das Ganze intensiver analysieren.

Idee: Hast Du  Git bei Dir laufen? Falls nein, dann bitte installieren und noch einmal den Adapter installieren bevor Du eventuell eine Testinstallation aufsetzt.

**Comment by Peter1980FFM** [comment]
seltsam.. jetzt habe ich das Git Paket nochmal Installiert und nun ging die Installation des Adapters..

**Comment by Steiger04** [comment]
Sehr gut, dann war irgendetwas mit Deinem Git grütze.
