### ISSUE TITLE
MiLight IBOX 2 und FUT 037

### ISSUE THREAD

**Issue by Peter1980FFM** [Steiger04/ioBroker.milight-smart-light#32]
Habe hier eine MiLight IBOX 2 und FUT 037 RGB Controler,
der Adapter zeit mir an, das er mit der IBOX 2 Verbunden ist, jedoch kommen keine Komandos am Stribe an..
Wenn ich das über die MI Light App am Handy mache geht es? bin etwas Ratlos

**Comment by Steiger04** [comment]
Hast Du als Typ(Zone) auch RGB(W) eingestellt und die richtige Zonennummer ausgewählt und ganz wichtig auch die Zone aktiviert?

**Comment by Peter1980FFM** [comment]
![image](https://user-images.githubusercontent.com/45266139/82834118-71e58c80-9ec0-11ea-993f-528ef23b57a3.png)
![image](https://user-images.githubusercontent.com/45266139/82834140-845fc600-9ec0-11ea-8c45-8611a77f16e5.png)
Ich denke Ja

**Comment by Steiger04** [comment]
Der Port ist falsch. Richtiger Port ist: 5987

**Comment by Peter1980FFM** [comment]
Leider auch so keine Möglichkeit..
![image](https://user-images.githubusercontent.com/45266139/82834519-a7d74080-9ec1-11ea-99a9-ff0ed9e455c6.png)

![image](https://user-images.githubusercontent.com/45266139/82834470-7d858300-9ec1-11ea-980a-3eae859368ee.png)
![image](https://user-images.githubusercontent.com/45266139/82834493-90985300-9ec1-11ea-9b4f-b1373ef19053.png)

**Comment by Steiger04** [comment]
Ist im Admin-Log irgendetwas rot? Wenn ja bitte die Instanz noch einmal starten.

**Comment by Peter1980FFM** [comment]
Leider nicht
![image](https://user-images.githubusercontent.com/45266139/82835671-018d3a00-9ec5-11ea-834c-796a618ffec1.png)
Am besten ich schmeiße den milight müll weg....

**Comment by Steiger04** [comment]
@Peter1980FFM Ein Hinweis noch für Dich: Du musst bei Verwendung des Typ (Zone) = RGB(W) die Zone in der original Milight-App auch mit der "richtigen" Fernbedienung angelernt haben.

![image](https://user-images.githubusercontent.com/17086944/82898108-ff74bb00-9f58-11ea-9eee-44d5e2e66208.png)

D.h. bei RGB(W) mit der linken Fernbedienung und bei fullColor und fullColor8Zone mit der rechten Fernbedienung. Solltest Du dies nicht getan haben, empfehle ich Dir dies einmal zu probieren.

Bei mir funktioniert genau Deine Konstellation völlig problemlos.

**Comment by Sundancer78** [comment]
bei mir funktioniert der Adapter seit dem Update 03 oder 04 nicht mehr, habe ihn schon komplett neu aufgesetzt und mehrmals eingerichtet. die IP der iBox2 wird automatisch gefunden, die Objekte werden auch alle angelegt so wie es sonst auch der Fall war, schalte ich ein Status passiert bei dem Stripe nix. per App funktioniert alles, Hhabe mittlerweile den anderen Mi-light Adapter installiert und der funktioniert. Soweit ich mich erinnere gab es in den Adaptereinstellungen mehrere Stripe Varianten, die RGB(WW)/Dimmer? fehlt, dafür jetzt nur noch RGB(W)/Dimmer? 
Im Admin- LOG ist auch nix rot, so langsam bin ich auch ratlos.

**Comment by Steiger04** [comment]
@Sundancer78 Beim Update auf v0.6.0 musst Du zwingend wie **[>>hier<<](https://steiger04.github.io/milight-smart-light-doku/versionen/#update-auf-v0-6-0)** beschrieben vorgehen, oder die Instanz komplett neu anlegen und Du musst die Zone mit der richtigen Fernbedienung in der Original Milight-App angelernt haben. Wenn Du das alles gemacht hast, dann funktioniert es auch, ansonsten hast Du noch irgendeinen Konfig-Fehler bei Dir drinnen. Wenn Du das alles gemacht hast und es dann immer noch nicht klappt brauche ich mehr Infos von Dir, oder Du bleibst, wenn Du die Abhänigkeiten der States untereinander nicht benötigst bei dem anderen Milight-Adapter.

**Comment by juwei80** [comment]
Bei mir funktionier es wie bei @Sundancer78 auch nicht. Ich habe die iBox2 heute geliefert bekommen, eingerichtet, mit der App kann ich es im WLAN steuern, die iBox2 wird vom Adapter auch gefunden, Port 5987 usw.. In der App kann ich die Zonen mit der ersten Fernbedienung (4-Zonen) bedienen, mit dem Adapter aber mit 4-Zonen und den Strips jeweils als RGB(W) und entsprechenden Zonen nicht. Warum?

Edit: ah, nochmal genau auf den Screenshot von @Steiger04 geschaut: das ist nicht die ganz linke Fernbedienung, sondern in der App die zweite von links. Unter dieser in der App nochmal alles neu angelernt und dann geht es auch mit dem Adapter!

**Comment by Steiger04** [comment]
Ich mach dann hier mal zu.
