### ISSUE TITLE
Missing New WL5 Controller 

### ISSUE THREAD

**Issue by hyperbit00** [Steiger04/ioBroker.milight-smart-light#33]
![image](https://user-images.githubusercontent.com/16324569/99592616-bc1f7480-29f0-11eb-9539-e257969b1e33.png)

There is a brand new controller Calles WL5.
is there a way to implement this ?

**Comment by Steiger04** [comment]
Unfortunately, there is currently no way to integrate the WL5 controller. You can read why this is so [here](https://steiger04.github.io/milight-smart-light-doku/introduction/).
