### ISSUE TITLE
URGENT!!

### ISSUE THREAD

**Issue by Apollon77** [Steiger04/ioBroker.milight-smart-light#35]
The repo is broken. The adapter type is now "general" in io-package wich is !== "lighting" as in repo and the Admin Image location is invalid.

Please fix in your repo or in iobroker repository!

Thank you

**Comment by Steiger04** [comment]
I hope I have everything fixed now.

**Comment by Apollon77** [comment]
Hm ... log still not correct

Icon of adapter milight-smart-light: https://raw.githubusercontent.com/Steiger04/ioBroker.milight-smart-light/master/admin/lib/images/milight-smart-light-md.png not getable

Or should we adjust the logo location in repo simply?

**Comment by Apollon77** [comment]
new image in admin is called .../admin/milight-smart-light.png

**Comment by Steiger04** [comment]
@Apollon77 Einmal kurz in german
Unter [http://download.iobroker.net/list.html](http://download.iobroker.net/list.htmll) wird auf milight-smart-light-md.png referenziert und unter [https://www.iobroker.net/#de/adapters/adapterref/iobroker.milight-smart-light/README.md](https://www.iobroker.net/#de/adapters/adapterref/iobroker.milight-smart-light/README.mdl) auf en/adapterref/iobroker.milight-smart-light/public/milight-smart-light-logo.png. Hier wird dann auch unter Information Version v0.2.7 benannt, aber unter Änderungsprotokoll die aktuelle README aus dem Master herangezogen (Soll das wirklich so sein?).

Woher nimmt denn das Repo unter [http://download.iobroker.net/list.html](http://download.iobroker.net/list.htmll) standardmäßig die Infos für das Logo? Wenn Du es händisch anpassen musst, dann bitte auf .../admin/milight-smart-light.png anpassen.

**Comment by Apollon77** [comment]
Steht im Repo drin. Schau mal in die Repo files beim Adapter

**Comment by Steiger04** [comment]
@Apollon77 Stimmt, ich erinnere mich. Danke! Ü50 ist halt doch scheiße :-)
