### ISSUE TITLE
update 0.6.0 - 1.01 failed

### ISSUE THREAD

**Issue by vr6syncro** [Steiger04/ioBroker.milight-smart-light#36]
**Describe the bug**  

Er updatet aber nimmt die neue Version nicht. Er schlägt das Update immer wieder vor. Ein neues UI kann ich auch nicht erkennen von daher denke ich die Version wird nicht richtig installiert.

**Screenshots & Logfiles**  

`

host.ioBroker | 2020-12-02 12:56:34.838 | info | iobroker exit 0
-- | -- | -- | --
host.ioBroker | 2020-12-02 12:56:33.826 | info | iobroker Adapter "milight-smart-light" updated
host.ioBroker | 2020-12-02 12:56:33.766 | info | iobroker upload [0] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/index_m.html index_m.html text/html
host.ioBroker | 2020-12-02 12:56:33.708 | info | iobroker upload [1] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/lib/images/milight-smart-light-md.png lib/images/milight-smart-light-md.png image/png
host.ioBroker | 2020-12-02 12:56:33.646 | info | iobroker upload [2] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/lib/images/milight-smart-light.png lib/images/milight-smart-light.png image/png
host.ioBroker | 2020-12-02 12:56:33.580 | info | iobroker upload [3] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/lib/js/msl-load-save.js lib/js/msl-load-save.js application/javascript
host.ioBroker | 2020-12-02 12:56:33.518 | info | iobroker upload [4] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/lib/js/msl-vue.js lib/js/msl-vue.js application/javascript
host.ioBroker | 2020-12-02 12:56:33.452 | info | iobroker upload [5] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/lib/js/vue/vue.min.2.6.11.js lib/js/vue/vue.min.2.6.11.js application/javascript
host.ioBroker | 2020-12-02 12:56:33.349 | info | iobroker upload [6] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/lib/js/vuelidate/validators.min.js lib/js/vuelidate/validators.min.js application/javascrip
host.ioBroker | 2020-12-02 12:56:33.273 | info | iobroker upload [7] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/lib/js/vuelidate/vuelidate.min.js lib/js/vuelidate/vuelidate.min.js application/javascript
host.ioBroker | 2020-12-02 12:56:33.017 | info | iobroker upload [8] milight-smart-light.admin /opt/iobroker/node_modules/iobroker.milight-smart-light/admin/words.js words.js application/javascript
host.ioBroker | 2020-12-02 12:56:32.944 | info | iobroker npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2020-12-02T11_56_32_927Z-debug.log
host.ioBroker | 2020-12-02 12:56:32.943 | info | iobroker
host.ioBroker | 2020-12-02 12:56:32.926 | info | iobroker npm ERR! notsup Unsupported engine for iobroker.milight-smart-light@1.0.1: wanted: {"node":">= 10.18.1","npm":">= 6.13.4","yarn":">= 1.21.1"} (current: {"node":"12.12.0","npm":"6.11.3"})npm
host.ioBroker | 2020-12-02 12:56:32.923 | info | iobroker npm ERR! code ENOTSUP
host.ioBroker | 2020-12-02 12:56:18.261 | info | iobroker npm install iobroker.milight-smart-light@1.0.1 --loglevel error --prefix "/opt/iobroker" (System call)
host.ioBroker | 2020-12-02 12:56:18.258 | info | iobroker NPM version: 6.11.3
octoprint.0 | 2020-12-02 12:56:18.208 | info | (32273) timeout of 2000ms exceeded
host.ioBroker | 2020-12-02 12:56:17.617 | info | iobroker Update milight-smart-light from @0.6.0 to @1.0.1
host.ioBroker | 2020-12-02 12:56:14.766 | info | iobroker upgrade milight-smart-light

`

**Comment by Steiger04** [comment]
Du nutzt gerade npm v6.11.3. Bitte auf eine Version npm >= v6.13.4 upgraden.

**Comment by vr6syncro** [comment]
Scheint zu funktionieren. Danke
