### ISSUE TITLE
Restart from time to time

### ISSUE THREAD

**Issue by n3roGit** [Steiger04/ioBroker.milight-smart-light#37]
milight-smart-light.1 | 2020-12-04 20:20:43.203 | info | (16447) starting. Version 0.2.7 in /opt/iobroker/node_modules/iobroker.milight-smart-light, node: v12.18.3, js-controller: 3.1.6
-- | -- | -- | --
milight-smart-light.1 | 2020-12-04 20:20:39.952 | info | (16417) Terminated (NO_ERROR): Without reason
milight-smart-light.1 | 2020-12-04 20:20:39.949 | info | (16417) terminating
milight-smart-light.1 | 2020-12-04 20:20:39.946 | error | at processTimers (internal/timers.js:492:7)
milight-smart-light.1 | 2020-12-04 20:20:39.946 | error | at listOnTimeout (internal/timers.js:549:17)
milight-smart-light.1 | 2020-12-04 20:20:39.946 | error | at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.milight-smart-light/node_modules/node-milight-promise/src/milight-v6-mixin.js:128:26)
milight-smart-light.1 | 2020-12-04 20:20:39.946 | error | (16417) Error: no response timeout
milight-smart-light.1 | 2020-12-04 20:20:39.946 | error | (16417) unhandled promise rejection: no response timeout

From time to time the adapter restarts.

**Comment by Steiger04** [comment]
The error has been fixed as of v0.6.0. You have to install the adapter from the latest repo. The current version is v1.0.1. You can find a German documentation [here](https://steiger04.github.io/milight-smart-light-doku/).
