### ISSUE TITLE
Name Reset to default

### ISSUE THREAD

**Issue by n3roGit** [Steiger04/ioBroker.milight-smart-light#38]
Since I am on version 0.6 the names I give to the datapoints are constantly reset to the default value. In the old version this was not the case.

![image](https://user-images.githubusercontent.com/8565847/102208882-46fc6d80-3ed0-11eb-8674-4f6a870a8bc9.png)

**Comment by Steiger04** [comment]
This only happens if you change the created zone.

**Comment by n3roGit** [comment]
No I have not adjusted anything.

**Comment by Steiger04** [comment]
Please describe the scenario when exactly a reset happens to you. At the moment I can't see why.

**Comment by n3roGit** [comment]
Hmm okay.
I updated to the 0.6 version because of reconnect problems. After upgrading this problem was fixed. But the custom names are gone. So I edited all entry's. But after some time. Maybe 1 day the custom names of the milight devices are resetted to default. At this time I tryed to set the custom names several times without positive result

**Comment by Steiger04** [comment]
You must have somehow changed a zone and then saved it. The adapter does not change any states by itself. Go there and uninstall all instances and also the adapter and then put on again.
