### ISSUE TITLE
Only Buttons supported?

### ISSUE THREAD

**Issue by vr6syncro** [Steiger04/ioBroker.milight-smart-light#4]
Hey in the objects there are only buttons. Is there a support for values?
Like Dimmer 10 or 10%?

Or is it impossible with the bridge?

**Comment by Steiger04** [comment]
You don't have only buttons for states in the objects (e.g. for brightness, hue, saturation, rgb, whiteTemperature you must use resonable values).

**Comment by vr6syncro** [comment]
moin, ich habe leider keiner dieser Datenpunkt. Weiße lampe kein rgb
https://screenshots.firefoxusercontent.com/images/05111bd9-7347-4baf-9db7-86d582268a0a.png

**Comment by Steiger04** [comment]
Für die weißen LEDs gibt es die Datenpunkte nur in der Rolle Button. Hintergrund ist die Umsetzung der Milight Protokollversionen V6 und legacy in der Node.js-Bibliothek von mwittig, die die Basis des Adapters bildet. Hier sind keine Prozentwerte vorgesehen und nach meinem Verständnis auch nicht möglich.
