### ISSUE TITLE
Instanzen-Config-Screen öffnet nicht

### ISSUE THREAD

**Issue by Tom-OOE** [Steiger04/ioBroker.milight-smart-light#42]
Ich möchte die Instanz eines Adapters konfigurieren. Die Konfigurationsseite öffnet sich, zeigt aber dann nur dauerhaft einen "Spinner" an. Eingabefelder oder Buttons sind nicht sichtbar. Das selbe Problem zeigt sich beim Öffnen der "mslfe for iobroker"-Website. Ich kann somit meine Adapter nicht mehr konfigurieren. 

Ich habe 8 Instanzen laufen. Alle funktionieren auch grundsätzlich (lassen sich halt jetzt nicht mehr konfigurieren). Experimentell habe ich eine 9. Instanz angelegt, die ich aber auch "im frischen Zustand" nicht konfigurieren kann. Seit wann die Konfiguration nicht mehr funktioniert, kann ich nicht sagen - vielleicht auch schon länger nicht. Der Adapter braucht ja nicht ständig eine neue Konfiguration. Die Erkenntnis, dass es ein Problem gibt, hatte ich erst mit der aktuellen Version (wollte nachsehen, ob sich etwas bei der Konfiguration geändert hat). 

Im Log ist nichts auffälliges zu sehen. 

**Expected behavior**  
Konfigurations-Screen öffnet sich.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/54640142/105574095-8a18ee80-5d62-11eb-89bd-742bc928e848.png)

**Versions:**  
 - Adapter version: 1.2.0 (aber auch ein Downgrade ändert nichts)
 - JS-Controller version: 3.1.6
 - Node version: 12.20.1
 - Operating system: Windows 10, 64bit

**Additional context**  
Abgesehen davon, dass die Lampen oft nicht auf Ein- oder Ausschaltbefehle reagieren (und ich habe schon vieles probiert um das zu beheben), läuft das System und auch der Adapter.

**Comment by Steiger04** [comment]
Mit den von Dir genannten Versionen (inkl. admin 4.2.1) sollte es keine Probleme geben. Bei mir läuft es wie es soll. Gibt es im Log noch Fehlermeldungen vom Adapter? Das die Lampen oft nicht auf Ein- und Ausschaltbefehle reagieren ist auch sehr merkwürdig und dürfte so pauschal nicht sein. Hast Du mal mit den "Befehlswiederholungen" und "Pause zwischen den Befehlen" experimentiert (s.a. [hier](https://steiger04.github.io/milight-smart-light-doku/admin/) )?
