### ISSUE TITLE
Das Webinterface startet nicht und signale werden nicht an die Lampen übergeben: Uncaught TypeError: e.ids.statevalues is undefined

### ISSUE THREAD

**Issue by milo1987** [Steiger04/ioBroker.milight-smart-light#43]
Guten Morgen, 

ich versuche seit gestern den Adapter ans laufen zu bekommen. Leider nur mit mäßigen Erfolg.

**Zum Setting:**
Die Milight IBox2 mit ein paar GU10 RGB(w) Lampen mittels der Milight3 App angelernt auf Zone1, in der milight app funktionieren diese auch

Aktuellerster milight-smart-light Adapter
NodeJS >12

**Problemdarstellung**
Ich kann den Adapter erfolgreich konfigurieren, bekomme in Iobroker selber keine Fehlermeldungen.
Wenn ich jedoch die http://10.22.2.20:4400/ aufrufe, so erhalte ich einen weißen Ladebalken, welcher sich im Kreis dreht und folgende Fehlermeldungen im Firefox Debugger (Chrome habe ich auch bereits getestet)

`Uncaught TypeError: e.ids.statevalues is undefined
    B http://10.22.2.20:4400/js/app.e3c98a91.js:1
    k http://10.22.2.20:4400/js/vendor.ac843413.js:20
    commit http://10.22.2.20:4400/js/vendor.ac843413.js:20
    commit http://10.22.2.20:4400/js/vendor.ac843413.js:20
    _withCommit http://10.22.2.20:4400/js/vendor.ac843413.js:20
    commit http://10.22.2.20:4400/js/vendor.ac843413.js:20
    commit http://10.22.2.20:4400/js/vendor.ac843413.js:20
    commit http://10.22.2.20:4400/js/vendor.ac843413.js:20
    re http://10.22.2.20:4400/js/app.e3c98a91.js:1
    O http://10.22.2.20:4400/js/vendor.ac843413.js:20
    dispatch http://10.22.2.20:4400/js/vendor.ac843413.js:20
    dispatch http://10.22.2.20:4400/js/vendor.ac843413.js:20
    onUpdate http://10.22.2.20:4400/js/app.e3c98a91.js:1
    init http://10.22.2.20:4400/js/app.e3c98a91.js:1
    emit http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onevent http://10.22.2.20:4400/js/vendor.ac843413.js:8
    onpacket http://10.22.2.20:4400/js/vendor.ac843413.js:8
    exports http://10.22.2.20:4400/js/vendor.ac843413.js:20
    emit http://10.22.2.20:4400/js/vendor.ac843413.js:60
    ondecoded http://10.22.2.20:4400/js/vendor.ac843413.js:25
    exports http://10.22.2.20:4400/js/vendor.ac843413.js:20
    emit http://10.22.2.20:4400/js/vendor.ac843413.js:25
    add http://10.22.2.20:4400/js/vendor.ac843413.js:25
    ondata http://10.22.2.20:4400/js/vendor.ac843413.js:25
    exports http://10.22.2.20:4400/js/vendor.ac843413.js:20
    emit http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onPacket http://10.22.2.20:4400/js/vendor.ac843413.js:60
    setTransport http://10.22.2.20:4400/js/vendor.ac843413.js:60
    emit http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onPacket http://10.22.2.20:4400/js/vendor.ac843413.js:1
    onData http://10.22.2.20:4400/js/vendor.ac843413.js:1
    onmessage http://10.22.2.20:4400/js/vendor.ac843413.js:1
    addEventListeners http://10.22.2.20:4400/js/vendor.ac843413.js:1
    doOpen http://10.22.2.20:4400/js/vendor.ac843413.js:1
    open http://10.22.2.20:4400/js/vendor.ac843413.js:1
    probe http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onOpen http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onHandshake http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onPacket http://10.22.2.20:4400/js/vendor.ac843413.js:60
    setTransport http://10.22.2.20:4400/js/vendor.ac843413.js:60
    emit http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onPacket http://10.22.2.20:4400/js/vendor.ac843413.js:1
    n http://10.22.2.20:4400/js/vendor.ac843413.js:1
    decodePayload http://10.22.2.20:4400/js/vendor.ac843413.js:25
    onData http://10.22.2.20:4400/js/vendor.ac843413.js:1
    doPoll http://10.22.2.20:4400/js/vendor.ac843413.js:60
    emit http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onData http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onLoad http://10.22.2.20:4400/js/vendor.ac843413.js:60
    onreadystatechange http://10.22.2.20:4400/js/vendor.ac843413.js:60
    create http://10.22.2.20:4400/js/vendor.ac843413.js:60
    f http://10.22.2.20:4400/js/vendor.ac843413.js:60
    request http://10.22.2.20:4400/js/vendor.ac843413.js:60
    doPoll http://10.22.2.20:4400/js/vendor.ac843413.js:60
    poll http://10.22.2.20:4400/js/vendor.ac843413.js:1
    doOpen http://10.22.2.20:4400/js/vendor.ac843413.js:1
    open http://10.22.2.20:4400/js/vendor.ac843413.js:1
    open http://10.22.2.20:4400/js/vendor.ac843413.js:60
    f http://10.22.2.20:4400/js/vendor.ac843413.js:60
    f http://10.22.2.20:4400/js/vendor.ac843413.js:60
    connect http://10.22.2.20:4400/js/vendor.ac843413.js:25
    p http://10.22.2.20:4400/js/vendor.ac843413.js:25
    p http://10.22.2.20:4400/js/vendor.ac843413.js:25
    c http://10.22.2.20:4400/js/vendor.ac843413.js:25
    init http://10.22.2.20:4400/js/app.e3c98a91.js:1
    e http://10.22.2.20:4400/js/app.e3c98a91.js:1
    e http://10.22.2.20:4400/js/app.e3c98a91.js:1
    l http://10.22.2.20:4400/js/vendor.ac843413.js:30
    k http://10.22.2.20:4400/js/vendor.ac843413.js:30
    e http://10.22.2.20:4400/js/vendor.ac843413.js:30
    n http://10.22.2.20:4400/js/vendor.ac843413.js:60
    s http://10.22.2.20:4400/js/vendor.ac843413.js:60
    promise callback*n http://10.22.2.20:4400/js/vendor.ac843413.js:60
    s http://10.22.2.20:4400/js/vendor.ac843413.js:60
    o http://10.22.2.20:4400/js/vendor.ac843413.js:60
    o http://10.22.2.20:4400/js/vendor.ac843413.js:60
    Ce http://10.22.2.20:4400/js/app.e3c98a91.js:1
    e http://10.22.2.20:4400/js/app.e3c98a91.js:1
    l http://10.22.2.20:4400/js/vendor.ac843413.js:30
    k http://10.22.2.20:4400/js/vendor.ac843413.js:30
    e http://10.22.2.20:4400/js/vendor.ac843413.js:30
    n http://10.22.2.20:4400/js/vendor.ac843413.js:60
    s http://10.22.2.20:4400/js/vendor.ac843413.js:60
    promise callback*n http://10.22.2.20:4400/js/vendor.ac843413.js:60
    s http://10.22.2.20:4400/js/vendor.ac843413.js:60
    o http://10.22.2.20:4400/js/vendor.ac843413.js:60
    o http://10.22.2.20:4400/js/vendor.ac843413.js:60
    ze http://10.22.2.20:4400/js/app.e3c98a91.js:1
    Oe http://10.22.2.20:4400/js/app.e3c98a91.js:1
    2f39 http://10.22.2.20:4400/js/app.e3c98a91.js:1
    a http://10.22.2.20:4400/js/app.e3c98a91.js:1
    0 http://10.22.2.20:4400/js/app.e3c98a91.js:1
    a http://10.22.2.20:4400/js/app.e3c98a91.js:1
    n http://10.22.2.20:4400/js/app.e3c98a91.js:1
    <anonymous> http://10.22.2.20:4400/js/app.e3c98a91.js:1
    <anonymous> http://10.22.2.20:4400/js/app.e3c98a91.js:1
app.e3c98a91.js:1:10140
`

Zudem kann ich die Lampen nicht über den Reiter Objekte steuern. Es erscheinen auch hier keine Logeinträge.

Angefügt habe ich mal ein paar Screenshots. Wahrscheinlich übersehe ich nur einen dummen Fehler... 

Danke schonmal für die Hilfe und vorallem für deine Arbeit an deinem Adapter!!!
![website](https://user-images.githubusercontent.com/42001654/107203079-3f9e9f80-69fb-11eb-85f5-fd9a294679db.PNG)
![zonen](https://user-images.githubusercontent.com/42001654/107203082-40cfcc80-69fb-11eb-968e-d878ce71b1d7.PNG)
![autoerkennung](https://user-images.githubusercontent.com/42001654/107203085-40cfcc80-69fb-11eb-9874-ef05bf26df6a.PNG)
![fehler detailiert](https://user-images.githubusercontent.com/42001654/107203086-40cfcc80-69fb-11eb-85d5-8936f5ab50a4.PNG)
![grundconfig](https://user-images.githubusercontent.com/42001654/107203087-41686300-69fb-11eb-9bc3-5cba8fb374b9.PNG)
![logs](https://user-images.githubusercontent.com/42001654/107203089-41686300-69fb-11eb-8c9b-a3a66d1f59cc.PNG)
![mslapp](https://user-images.githubusercontent.com/42001654/107203090-41686300-69fb-11eb-96c5-74401d8fa830.PNG)
![webadapter](https://user-images.githubusercontent.com/42001654/107203092-4200f980-69fb-11eb-9ee5-b5541161d08f.PNG)

**Comment by Steiger04** [comment]
Das ist ein ein Problem mit dem Socket. Du musst eine separate socketio-Instanz (Adapter socket.io) erzeugen und nicht die interne Instanz des web-Adapters nutzen. Ganz wichtig: nutzte die Version 3.0.12. Bei dem aktuellen socket.io-Adapter wurde etwas geändert (analog im aktuellen web-Adapter), was zu den Fehlern führt. Das werde ich demnächst in meinem Adpater patchen. Bis dahin kannst Du aber so vorgehen wie beschrieben. Das hat keine nagativen Auswirkungen.

**Comment by milo1987** [comment]
Alles klar, mache ich!
Vielen Dank für den Hinweis und mach weiter so!
