### ISSUE TITLE
Kanäle werden gelöscht

### ISSUE THREAD

**Issue by vr6syncro** [Steiger04/ioBroker.milight-smart-light#5]
Ich habe ein Problem habe nun 3 Geräte. Die ersten beiden legt er an ohne zu mucken. Legt man nun ein weiteres an löscht er das auf Kanal 2. Unmöglich 3 anzulegen.

**Comment by vr6syncro** [comment]
http://forum.iobroker.net/viewtopic.php?f=22&t=8434

Problem mit 2 fast identischen Namen

**Comment by Steiger04** [comment]
Da scheint es noch ein Problem mit Umlauten zu geben. Wenn Du Küche mit ue schreibst, dann sollte es aber gehen. Habe das Problem jetzt auf meiner ToDo-Liste und werde es in einer der nächsten Versionen fixen.
